version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mounts source code (including SQLite)
    env_file:
      - .env  # Load API credentials from .env